version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always

  dashboard:
    build: ./dashboard
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: always

